# Generated by Django 3.2.24 on 2024-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_trainerreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerreview',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='trainer/images/'),
        ),
    ]
