# Generated by Django 3.2.24 on 2024-02-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_alter_trainerreview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerreview',
            name='image',
        ),
        migrations.AddField(
            model_name='trainerreview',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
