# Generated by Django 3.2.24 on 2024-02-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_auto_20240222_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerreview',
            name='status',
        ),
        migrations.AddField(
            model_name='trainerreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
