# Generated by Django 3.2.24 on 2024-02-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20240227_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerreview',
            name='approved',
        ),
    ]
