# Generated by Django 3.2.24 on 2024-02-29 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0014_alter_trainerreview_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerreview',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='trainerreview',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
