# Generated by Django 3.2.24 on 2024-02-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('connect', '0016_alter_trainerreview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerreview',
            name='user',
        ),
        migrations.AddField(
            model_name='trainerreview',
            name='user_profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
