# Generated by Django 3.2.24 on 2024-02-29 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_auto_20240229_1542'),
        ('connect', '0018_rename_user_profile_trainerreview_user'),
    ]

    operations = [
    ]
