# Generated by Django 3.2.24 on 2024-02-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20240220_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='image',
        ),
    ]
