# Generated by Django 3.2.24 on 2024-02-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='personal_training_session',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='PersonalTrainingSession',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
